cmake_minimum_required(VERSION 3.10)
project(BasicLanguageFacilities)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(1_fistcpp 1_fistcpp.cpp)
add_executable(2_IO 2_IO.cpp)
add_executable(3_pointers 3_pointers.cpp)
add_executable(4_pointers 4_pointers.cpp)
add_executable(5_funcPointers 5_funcPointers.cpp)
